rights.checkbox.activate=הפעל
rights.help.bansnotwork=הגבלות לא עובדות על:
rights.help.whitelisthelp=רשימה לבנה(מקש ימני למחיקה):
rights.coulmn.nickname=שם משתמש
rights.coulmn.steamid=SteamID
rights.help.listhelp=לפתוח רשימת שחקנים:
rights.help.ban=לחסום:
rights.checkbox.spawnmenu=להשתמש ב - spawn menu
rights.checkbox.property=להשתמש ב - C menu
rights.checkbox.weapons=השגת נשקים
rights.checkbox.physgun=להשתמש ב - physgun
rights.checkbox.gravitygun=להשתמש ב - gravity gun
rights.checkbox.toolgun=להשתמש ב - toolgun
rights.checkbox.pickup=הרמת פריטים
rights.checkbox.break=פגיעה בפריטים
rights.checkbox.maxspeed=הגבלת מהירות
rights.numslider.maxspeed=מהירות מקסימלית
rights.checkbox.noclip=Noclip