rights.checkbox.activate=Включить
rights.help.bansnotwork=Запрет не работает на:
rights.help.whitelisthelp=Исключения (ПКМ чтобы удалить):
rights.coulmn.nickname=Никнейм
rights.coulmn.steamid=SteamID
rights.help.listhelp=Открыть список игроков:
rights.help.ban=Заблокировать:
rights.checkbox.spawnmenu=Спавнменю
rights.checkbox.property=Контекстное меню
rights.checkbox.weapons=Взятие оружия из спавнменю
rights.checkbox.physgun=Физган
rights.checkbox.gravitygun=Грави пушка
rights.checkbox.toolgun=Тулган
rights.checkbox.pickup=Подбор предметов
rights.checkbox.break=Урон объектам
rights.checkbox.maxspeed=Ограничение скорости
rights.numslider.maxspeed=Макс. скорость
rights.checkbox.noclip=Режим полёта