rights.checkbox.activate=Active
rights.help.bansnotwork=Bans don't work on:
rights.help.whitelisthelp=Whitelist(RBM to delete):
rights.coulmn.nickname=Nickname
rights.coulmn.steamid=SteamID
rights.help.listhelp=Open players list:
rights.help.ban=Ban:
rights.checkbox.spawnmenu=Using spawn menu
rights.checkbox.property=Using C menu
rights.checkbox.weapons=Geting weapons
rights.checkbox.physgun=Using physgun
rights.checkbox.gravitygun=Using gravity gun
rights.checkbox.toolgun=Using toolgun
rights.checkbox.pickup=Pickup items
rights.checkbox.break=Damage objects
rights.checkbox.maxspeed=Speed limit
rights.numslider.maxspeed=Max speed
rights.checkbox.noclip=Noclip